sudo: required
services:
  - docker

before_install:
  - docker build -t vacaccdevops/docker-react -f Dockerfile.dev .

script:
  - docker run vacaccdevops/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-495611433687"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"